apiVersion: v1
kind: Service
metadata:
  name: mkdocs-service
spec:
  selector:
    app: mkdocs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Or "NodePort" for local environments
