apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs-deployment
  labels:
    app: mkdocs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkdocs
  template:
    metadata:
      labels:
        app: mkdocs
    spec:
      containers:
      - name: mkdocs
        image: your-dockerhub-username/mkdocs-site:latest  #TEMPORARY
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
