apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort  # Exposes the frontend on a Minikube port
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30000  # Access frontend on localhost:30000
